<LoginPage>:
    FloatLayout:
            canvas:
                Rectangle:
                    size: self.size
                    pos: self.pos
                    source: "icones/bg1.png"
            
            # página
            Label:
                text: "CONTROLE DE [color=#00CFDB]VENDAS HASHTAG[/color]"
                bold: True
                markup: True
                pos_hint: {"right": 0.9, "top":0.9}
                size_hint: 0.8, 0.2
